Fixes issue #10
anxdpanic/plugin.video.youtube pull request #89
Opened 2021-02-09 02:55 UTC by thomazz-nl

Issue was caused by two thing:
1. Google has some bad encoded characters in the response of get_embed_page(). I re-encoded to ascii while ignoring for bad characters and decoded it again to clean the response.
2. The regex to find the javascript https://www.youtube.com/s/player/xxxxxxxx/player_ias.vflset/xx_XX/base.js in the embed response was not working. My new regex works.

This is my first GitHub pull request/contribution to someone elses project. Please check carefully and let me know if I need to improve anything or do anything differently.

2021-02-09 19:02 UTC, anxdpanic requested changes
Thank you for looking into this!
Can you try the changes I suggested, your current iteration breaks one of my installs. The requested changes should hopefully cover everybody.

2021-02-09 19:02 UTC, anxdpanic commented on resources/lib/youtube_plugin/youtube/helper/video_info.py
> +        html = page_result.get('html').encode('ascii', 'ignore').decode('ascii')
```
        html = page_result.get('html')
        html = html.encode('utf8', 'ignore')
        html = html.decode('utf8')
```

2021-02-09 19:02 UTC, anxdpanic commented on resources/lib/youtube_plugin/youtube/helper/video_info.py
> +        found = re.search(r'<script src="(?P<url>[^"]+?player_[^"]+?/base\.js)"\s*>\s*</script\s*>', html)
```
        found = re.search(
            r'<script src="(?P<url>[^"]+?)"\s*name="player_[^/]+?/base"\s*>\s*</script\s*>', html
        )
        if not found:
            found = re.search(r'<script src="(?P<url>[^"]+?player_[^"]+?/base\.js)"\s*>\s*</script\s*>', html)
```

2021-02-11 01:57 UTC, thomazz-nl commented
Yes, your suggested changes fix the issue too. As content from the youtube page should be utf-8, this actually makes more sense.  The double regex check works too. I'm checking how I can merge your edits in my PR or how this works. Looking for "approve" button.

2021-02-11 04:26 UTC, anxdpanic approved these changes

2021-02-11 04:28 UTC, merged

2021-02-11 04:29 UTC, anxdpanic commented
Thank you again!

If you happen to have the inclination, could you dump the embed page html to a file and attach it to a message on this PR? No worries if not.

Will then be able to see about simplifying the regex.

2021-02-11 14:56 UTC, thomazz-nl commented
You're welcome. I generated the embed html page using this snippet:
`with io.open(r'C:\Users\User\Desktop\youtube_embed.html', 'w', encoding='utf-8', errors='ignore') as file:
    file.write(result.text)`

Here is the resulting html page: [youtube_embed_redacted.zip](https://github.com/anxdpanic/plugin.video.youtube/files/5966197/youtube_embed_redacted.zip). It's as original as possible (unformatted), but since reproducing the bug required me to be logged in and play an item from a playlist, the file contained some possibly identifying values. I carefully redacted these as they should be of no importance regarding the regex.

Maybe it's easier to use a regex to grab the base.js URL from the javascript "ytcfg" variable section? Given that Google doesn't change these often... Can you check if [this regex](https://github.com/thomazz-nl/plugin.video.youtube/commit/70e80da9ce0db6098bd2347f0f4675749bd8c28c) works for all your test-cases?